image: docker:latest
services:
  - docker:dind

stages:
  - test
  - build
  - deploy-staging
  - deploy-production

test:
  stage: test
  only:
    - master
    - merge_requests
  tags:
    - your-tag-here
  script:
    - echo run tests in this section!

build:
  stage: build
  only:
    - master
    - merge_requests
  tags:
    - your-tag-here
  environment:
    name: staging
    url: https://external-url.com
  script:
    - docker-compose -f ./deployment/docker-compose-server.yml build goliltemp

deploy_merge_request:
  stage: deploy-staging
  only:
    - merge_requests
  tags:
    - your-tag-here
  environment:
    name: staging
    url: https://external-url.com
  script:
    - docker-compose -f ./deployment/docker-compose-server.yml  up --build --force-recreate --remove-orphans -d
    - docker-compose -f ./deployment/docker-compose-server.yml logs --tail=20 goliltemp
    - docker image prune -f
    - sleep 10 && curl -X GET http://localhost:$INTERNAL_PORT/ping
  when: manual

deploy_staging:
  stage: deploy-staging
  only:
    - master
  tags:
    - your-tag-here
  environment:
    name: staging
    url: https://external-url.com
  script:
    - docker-compose -f ./deployment/docker-compose-server.yml up --build --force-recreate --remove-orphans -d
    - docker-compose -f ./deployment/docker-compose-server.yml logs --tail=20 goliltemp
    - docker image prune -f
    - sleep 10 && curl -X GET http://localhost:$INTERNAL_PORT/ping
  when: manual
